name: Publish Draft Release

on:
  schedule:
    - cron: '30 9 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Draft Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
